name: Build and Release AppImage for Linux

permissions:
  contents: write

on:
  push:
    branches:
     - autobuild
    tags:
      - 'v*' # run on every tag pushed to master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Qt environment
    - name: Set up Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.*' # Replace with your Qt version
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential cmake \
          qtbase5-dev qttools5-dev-tools \
          libx11-dev libxext-dev libxrandr-dev \
          libgl1-mesa-dev zlib1g-dev \
          patchelf fuse

    # Build the application
    - name: Build application
      run: |
        mkdir build
        cd build
        qmake .. -spec linux-g++ CONFIG+=release
        make -j$(nproc)

    # Package as AppImage
    - name: Package as AppImage
      run: |
        wget -q https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
        mkdir -p AppDir/usr/bin
        cp build/cob-taylor-games AppDir/usr/bin/
        mkdir -p AppDir/usr/share/applications
        cp appimage/cob-taylor-games.desktop AppDir/usr/share/applications/
        mkdir -p AppDir/usr/share/applications/icons/hicolor/64x64/apps
        cp appimage/cob-taylor-games.png AppDir/usr/share/applications/icons/hicolor/64x64/apps
        mkdir -p AppDir/usr/share/doc/libc6
        touch AppDir/usr/share/doc/libc6/copyright
        ./linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/share/applications/cob-taylor-games.desktop -appimage -unsupported-allow-new-glibc -extra-plugins=platforms.qml,quickwidgets

    # Upload AppImage to GitHub release
    - name: Upload AppImage to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: Taylor_Games_Kiosk-*-x86_64.AppImage
