name: Build and Release AppImage for Linux

on:
  push:
    branches:
     - autobuild
    tags:
      - '*' # run on every tag pushed to master

jobs:
  build:
    runs-on: archlinux-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo pacman -Syu --noconfirm git make cmake gcc qt6-base qt6-declarative which

    # Build the application
    - name: Build application
      run: |
        mkdir build
        cd build
        /usr/lib/qt6/bin/qmake .. -spec linux-g++ CONFIG+=release
        make -j$(nproc)

    # Package as AppImage
    - name: Package as AppImage
      run: |
        wget -q https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
        mkdir -p AppDir/usr/bin
        cp build/myapp AppDir/usr/bin/
        ./linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/bin/myapp -appimage

    # Upload AppImage to GitHub release
    - name: Upload AppImage to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: MyApp-x86_64.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
